% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Mar-2022 20:46:45
%  MATLAB version: 9.11.0.1873467 (R2021b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('synth4000.mat');

adja = saveVarsMat.adja; % <4000x4000 double> 元素太多

clear saveVarsMat;
